class TaskNotFoundError(Exception):
    """Исключение для отсутствующей задачи."""
    pass
